### ISSUE TITLE
您好，有些疑问想向您请教。

### ISSUE THREAD

**Issue by JiaJn** [JerryLiao26/drcom-py#1]
您好，同是深大的学生，我是电脑小白，请教下下面这段需要自己修改哪些数据改成自己可以用的？感激不尽。
# Global params

version = "0.1release-em-20160526"
param_num = len(sys.argv)
self_name = sys.argv[0]
file_path = os.path.expanduser("~") + "/.drcom/drcom.config" # Create config file under ~/.drcom/
auth_url = "http://192.168.254.220/a70.htm"
api_site = "http://api.jerryliao.cn/" # Default api url
api_type = "php" # Requested api file type
stu_no = "jf"
pwd = "jf"

**Comment by JerryLiao26** [comment]
@JiaJn 抱歉Github消息通知没有收到。如果是深大的话上面的数据可以不用修改，你要做的是安装在Linux上然后运行drcom -c修改帐号密码就可以。也可以直接修改上面的stu_no为你的卡号，pwd为查询密码

**Comment by JiaJn** [comment]
非常感谢您的帮助，我是打算把放进openwrt的无线路由器里面运行，不知auth_url =“ http://192.168.254.220/a70.htm ” 这个网址是从哪里获取的？如果不同宿舍楼的认证设备不同，这个网址是否需要修改？

**Comment by JiaJn** [comment]
root@OpenWrt:~# python /usr/drcom.py&
root@OpenWrt:~# Traceback (most recent call last):
  File "/usr/drcom.py", line 90, in <module>
    confirm()
  File "/usr/drcom.py", line 59, in confirm
    load_config()
  File "/usr/drcom.py", line 42, in load_config
    set_config()
  File "/usr/drcom.py", line 54, in set_config
    with open(file_path, 'w') as out_config:
IOError: [Errno 2] No such file or directory: '/root/.drcom/drcom.config'
运行的时候出现这个错误。

**Comment by JerryLiao26** [comment]
@JiaJn 你好，最简单获取认证网址的方式就是直接连到校园网然后在浏览器中随意输入一个网址，一般就会自动跳转到认证页面，然后将auth_url替换就可以了。
出现这个错误应该是找不到配置文件，你到/root/.drcom/下看看有没有drcom.config这个文件

**Comment by JiaJn** [comment]
十分感谢您，可以用路由器正确上网了。

**Comment by JerryLiao26** [comment]
@JiaJn 很高兴能够帮到你
